In [1]:
import numpy as np
import pandas as pd
import janitor

In [2]:
race = pd.read_csv('data/race_ethn.csv', skiprows=1)

In [3]:
race.head()

,Geography,Geographic Area Name,!!Total:,!!Total:!!Hispanic or Latino,!!Total:!!Not Hispanic or Latino:,!!Total:!!Not Hispanic or Latino:!!Population of one race:,!!Total:!!Not Hispanic or Latino:!!Population of one race:!!White alone,!!Total:!!Not Hispanic or Latino:!!Population of one race:!!Black or African American alone,!!Total:!!Not Hispanic or Latino:!!Population of one race:!!American Indian and Alaska Native alone,!!Total:!!Not Hispanic or Latino:!!Population of one race:!!Asian alone,...,!!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of five races:,!!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of five races:!!White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander,!!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of five races:!!White; Black or African American; American Indian and Alaska Native; Asian; Some Other Race,!!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of five races:!!White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race,!!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of five races:!!White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,!!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of five races:!!White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,!!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of five races:!!Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,!!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of six races:,!!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of six races:!!White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,Unnamed: 75
0,0500000US01001,"Autauga County, Alabama",58805,2117,56688,54198,41582,11352,184,873,...,0,0,0,0,0,0,0,0,0,NaN
1,0500000US01003,"Baldwin County, Alabama",231767,12686,219081,208713,186495,18001,1291,2029,...,0,0,0,0,0,0,0,0,0,NaN
2,0500000US01005,"Barbour County, Alabama",25223,1510,23713,23160,11086,11850,58,103,...,2,2,0,0,0,0,0,0,0,NaN
3,0500000US01007,"Bibb County, Alabama",22293,740,21553,20953,16442,4390,39,26,...,0,0,0,0,0,0,0,0,0,NaN
4,0500000US01009,"Blount County, Alabama",59134,5771,53363,51063,49764,826,188,174,...,1,0,0,1,0,0,0,0,0,NaN

In [4]:
race.shape[0]

3221

In [5]:
race_clean = race.clean_names()
race_clean.head()

,geography,geographic_area_name,_!!total_,_!!total_!!hispanic_or_latino,_!!total_!!not_hispanic_or_latino_,_!!total_!!not_hispanic_or_latino_!!population_of_one_race_,_!!total_!!not_hispanic_or_latino_!!population_of_one_race_!!white_alone,_!!total_!!not_hispanic_or_latino_!!population_of_one_race_!!black_or_african_american_alone,_!!total_!!not_hispanic_or_latino_!!population_of_one_race_!!american_indian_and_alaska_native_alone,_!!total_!!not_hispanic_or_latino_!!population_of_one_race_!!asian_alone,...,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_!!white;_black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_!!white;_black_or_african_american;_american_indian_and_alaska_native;_asian;_some_other_race,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_!!white;_black_or_african_american;_american_indian_and_alaska_native;_native_hawaiian_and_other_pacific_islander;_some_other_race,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_!!white;_black_or_african_american;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_!!white;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_!!black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_six_races_,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_six_races_!!white;_black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,unnamed_75
0,0500000US01001,"Autauga County, Alabama",58805,2117,56688,54198,41582,11352,184,873,...,0,0,0,0,0,0,0,0,0,NaN
1,0500000US01003,"Baldwin County, Alabama",231767,12686,219081,208713,186495,18001,1291,2029,...,0,0,0,0,0,0,0,0,0,NaN
2,0500000US01005,"Barbour County, Alabama",25223,1510,23713,23160,11086,11850,58,103,...,2,2,0,0,0,0,0,0,0,NaN
3,0500000US01007,"Bibb County, Alabama",22293,740,21553,20953,16442,4390,39,26,...,0,0,0,0,0,0,0,0,0,NaN
4,0500000US01009,"Blount County, Alabama",59134,5771,53363,51063,49764,826,188,174,...,1,0,0,1,0,0,0,0,0,NaN

In [6]:
race_clean.drop('unnamed_75', axis=1, inplace=True)

/var/folders/rz/h3gzrv2j09s6d_5vmn0bglw40000gn/T/ipykernel_73619/1540121687.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_clean.drop('unnamed_75', axis=1, inplace=True)

In [7]:
# drop rows with NAs
print(race_clean.isna().sum())
race_clean = race_clean.dropna()
race_clean.head()

geography                                                                                                                                                                                                                                  0
geographic_area_name                                                                                                                                                                                                                       0
_!!total_                                                                                                                                                                                                                                  0
_!!total_!!hispanic_or_latino                                                                                                                                                                                                              0
_!!total_!!not_hispanic_or_latino_                                                                                                                                                                                                         0
                                                                                                                                                                                                                                          ..
_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_!!white;_black_or_african_american;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race                                      0
_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_!!white;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race                              0
_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_!!black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race          0
_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_six_races_                                                                                                                                             0
_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_six_races_!!white;_black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race    0
Length: 75, dtype: int64

,geography,geographic_area_name,_!!total_,_!!total_!!hispanic_or_latino,_!!total_!!not_hispanic_or_latino_,_!!total_!!not_hispanic_or_latino_!!population_of_one_race_,_!!total_!!not_hispanic_or_latino_!!population_of_one_race_!!white_alone,_!!total_!!not_hispanic_or_latino_!!population_of_one_race_!!black_or_african_american_alone,_!!total_!!not_hispanic_or_latino_!!population_of_one_race_!!american_indian_and_alaska_native_alone,_!!total_!!not_hispanic_or_latino_!!population_of_one_race_!!asian_alone,...,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_four_races_!!american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_!!white;_black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_!!white;_black_or_african_american;_american_indian_and_alaska_native;_asian;_some_other_race,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_!!white;_black_or_african_american;_american_indian_and_alaska_native;_native_hawaiian_and_other_pacific_islander;_some_other_race,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_!!white;_black_or_african_american;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_!!white;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_five_races_!!black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_six_races_,_!!total_!!not_hispanic_or_latino_!!population_of_two_or_more_races_!!population_of_six_races_!!white;_black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race
0,0500000US01001,"Autauga County, Alabama",58805,2117,56688,54198,41582,11352,184,873,...,0,0,0,0,0,0,0,0,0,0
1,0500000US01003,"Baldwin County, Alabama",231767,12686,219081,208713,186495,18001,1291,2029,...,0,0,0,0,0,0,0,0,0,0
2,0500000US01005,"Barbour County, Alabama",25223,1510,23713,23160,11086,11850,58,103,...,0,2,2,0,0,0,0,0,0,0
3,0500000US01007,"Bibb County, Alabama",22293,740,21553,20953,16442,4390,39,26,...,0,0,0,0,0,0,0,0,0,0
4,0500000US01009,"Blount County, Alabama",59134,5771,53363,51063,49764,826,188,174,...,0,1,0,0,1,0,0,0,0,0

In [8]:
race_clean.columns = race_clean.columns.str.replace("!!", "_", regex=False)
race_clean.columns = race_clean.columns.str.replace("__", "_", regex=False)
race_clean.columns = race_clean.columns.str.replace("_total_", "total_", regex=False)

In [9]:
race_clean.head()

,geography,geographic_area_name,total_,total_hispanic_or_latino,total_not_hispanic_or_latino_,total_not_hispanic_or_latino_population_of_one_race_,total_not_hispanic_or_latino_population_of_one_race_white_alone,total_not_hispanic_or_latino_population_of_one_race_black_or_african_american_alone,total_not_hispanic_or_latino_population_of_one_race_american_indian_and_alaska_native_alone,total_not_hispanic_or_latino_population_of_one_race_asian_alone,...,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_four_races_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_five_races_,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_five_races_white;_black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_five_races_white;_black_or_african_american;_american_indian_and_alaska_native;_asian;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_five_races_white;_black_or_african_american;_american_indian_and_alaska_native;_native_hawaiian_and_other_pacific_islander;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_five_races_white;_black_or_african_american;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_five_races_white;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_five_races_black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_six_races_,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_six_races_white;_black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race
0,0500000US01001,"Autauga County, Alabama",58805,2117,56688,54198,41582,11352,184,873,...,0,0,0,0,0,0,0,0,0,0
1,0500000US01003,"Baldwin County, Alabama",231767,12686,219081,208713,186495,18001,1291,2029,...,0,0,0,0,0,0,0,0,0,0
2,0500000US01005,"Barbour County, Alabama",25223,1510,23713,23160,11086,11850,58,103,...,0,2,2,0,0,0,0,0,0,0
3,0500000US01007,"Bibb County, Alabama",22293,740,21553,20953,16442,4390,39,26,...,0,0,0,0,0,0,0,0,0,0
4,0500000US01009,"Blount County, Alabama",59134,5771,53363,51063,49764,826,188,174,...,0,1,0,0,1,0,0,0,0,0

Create variables of total and proportion of at least part Black and Asian, respectively

In [10]:
black_cols = [col for col in race_clean.columns if "black_or_african_american" in col.lower()]
asian_cols = [col for col in race_clean.columns if "asian" in col.lower()]

In [11]:
race_clean["total_black_any"] = race_clean[black_cols].sum(axis=1)
race_clean["total_asian_any"] = race_clean[asian_cols].sum(axis=1)

In [12]:
race_clean[black_cols]

,total_not_hispanic_or_latino_population_of_one_race_black_or_african_american_alone,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_two_races_white;_black_or_african_american,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_two_races_black_or_african_american;_american_indian_and_alaska_native,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_two_races_black_or_african_american;_asian,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_two_races_black_or_african_american;_native_hawaiian_and_other_pacific_islander,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_two_races_black_or_african_american;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_three_races_white;_black_or_african_american;_american_indian_and_alaska_native,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_three_races_white;_black_or_african_american;_asian,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_three_races_white;_black_or_african_american;_native_hawaiian_and_other_pacific_islander,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_three_races_white;_black_or_african_american;_some_other_race,...,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_four_races_black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_four_races_black_or_african_american;_american_indian_and_alaska_native;_asian;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_four_races_black_or_african_american;_american_indian_and_alaska_native;_native_hawaiian_and_other_pacific_islander;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_four_races_black_or_african_american;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_five_races_white;_black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_five_races_white;_black_or_african_american;_american_indian_and_alaska_native;_asian;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_five_races_white;_black_or_african_american;_american_indian_and_alaska_native;_native_hawaiian_and_other_pacific_islander;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_five_races_white;_black_or_african_american;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_five_races_black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_six_races_white;_black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race
0,11352,521,47,54,19,43,50,9,0,1,...,0,0,0,0,0,0,0,0,0,0
1,18001,1873,119,71,8,95,173,48,8,24,...,1,0,0,0,0,0,0,0,0,0
2,11850,226,25,0,6,24,12,0,0,0,...,0,0,0,0,2,0,0,0,0,0
3,4390,165,16,4,0,0,13,0,0,4,...,0,0,0,0,0,0,0,0,0,0
4,826,316,0,3,0,17,27,4,1,3,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,31,4,2,2,0,1,2,0,0,2,...,0,0,0,0,0,0,0,0,0,0
3217,47,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3218,3,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3219,12,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3220,11,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
race_clean[["total_black_any", "total_asian_any"]]

      total_black_any  total_asian_any
0               12109             1313
1               20446             3376
2               12145              136
3                4598               45
4                1211              338
...               ...              ...
3216               47               26
3217               48                3
3218                4                2
3219               13                9
3220               15               17

[3221 rows x 2 columns]

In [14]:
race_clean['prop_black'] = race_clean['total_black_any']/race_clean['total_']
race_clean['prop_asian'] = race_clean['total_asian_any']/race_clean['total_']

In [15]:
race_clean['prop_hispanic_or_latino'] = race_clean['total_hispanic_or_latino']/race_clean['total_']

In [16]:
race_clean.head()

,geography,geographic_area_name,total_,total_hispanic_or_latino,total_not_hispanic_or_latino_,total_not_hispanic_or_latino_population_of_one_race_,total_not_hispanic_or_latino_population_of_one_race_white_alone,total_not_hispanic_or_latino_population_of_one_race_black_or_african_american_alone,total_not_hispanic_or_latino_population_of_one_race_american_indian_and_alaska_native_alone,total_not_hispanic_or_latino_population_of_one_race_asian_alone,...,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_five_races_white;_black_or_african_american;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_five_races_white;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_five_races_black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_six_races_,total_not_hispanic_or_latino_population_of_two_or_more_races_population_of_six_races_white;_black_or_african_american;_american_indian_and_alaska_native;_asian;_native_hawaiian_and_other_pacific_islander;_some_other_race,total_black_any,total_asian_any,prop_black,prop_asian,prop_hispanic_or_latino
0,0500000US01001,"Autauga County, Alabama",58805,2117,56688,54198,41582,11352,184,873,...,0,0,0,0,0,12109,1313,0.205918,0.022328,0.036000
1,0500000US01003,"Baldwin County, Alabama",231767,12686,219081,208713,186495,18001,1291,2029,...,0,0,0,0,0,20446,3376,0.088218,0.014566,0.054736
2,0500000US01005,"Barbour County, Alabama",25223,1510,23713,23160,11086,11850,58,103,...,0,0,0,0,0,12145,136,0.481505,0.005392,0.059866
3,0500000US01007,"Bibb County, Alabama",22293,740,21553,20953,16442,4390,39,26,...,0,0,0,0,0,4598,45,0.206253,0.002019,0.033194
4,0500000US01009,"Blount County, Alabama",59134,5771,53363,51063,49764,826,188,174,...,0,0,0,0,0,1211,338,0.020479,0.005716,0.097592

Create fips variable

In [17]:
race_clean['fips'] = race_clean.geography.astype(str).str[-5:]

In [18]:
race_clean.to_csv('data/race_ethn_cleaned.csv', index=False)